CREATE TABLE OKT
	(
	OktID	    INT NOT NULL AUTO_INCREMENT,
	Dato		DATE,
	Tidspunkt	TIME,
	Varighet	TIME,
	Prestasjon	INT,
    CHECK (Prestasjon >= 1 AND Prestasjon <= 10),
	Form		INT,  
    CHECK (Form >= 1 AND Form <= 10),
	PRIMARY KEY(OktID)
	);

CREATE TABLE NOTAT
	(
	NotatID		INT	NOT NULL AUTO_INCREMENT,
    OktID       INT NOT NULL,
	Treningsformal	TEXT,
	PRIMARY KEY(NotatID),
	FOREIGN KEY(OktID) REFERENCES OKT(OktID) ON UPDATE CASCADE ON DELETE CASCADE
	);

CREATE TABLE OVELSE
	(
	OvelseID	INT	NOT NULL AUTO_INCREMENT,
	Navn		TINYTEXT,
	PRIMARY KEY(OvelseID)
	);

CREATE TABLE FRIOVELSE
	(
	OvelseID	INT	NOT NULL,
	Beskrivelse	TEXT,
	PRIMARY KEY (OvelseID),
	FOREIGN KEY (OvelseID) REFERENCES Ovelse(ovelseID) ON UPDATE CASCADE ON DELETE CASCADE
	);

CREATE TABLE APPARAT
	(
	ApparatID	INT	NOT NULL AUTO_INCREMENT,
	Navn		TINYTEXT,
	Beskrivelse	TEXT,
	PRIMARY KEY(ApparatID)
	);

CREATE TABLE APPARATOVELSE
	(
	OvelseID	INT	NOT NULL,
	AntallKilo	INT,
	AntallSett	INT,
	ApparatID	INT	NOT NULL,
	PRIMARY KEY (OvelseID),
	FOREIGN KEY (OvelseID) REFERENCES Ovelse(ovelseID)  ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(ApparatID) REFERENCES APPARAT(ApparatID)  ON UPDATE CASCADE ON DELETE CASCADE
	);

CREATE TABLE OVELSESGRUPPE	
	(
	GruppeID	INT NOT NULL AUTO_INCREMENT,
	Navn		TINYTEXT,
	PRIMARY KEY(GruppeID)
	);

CREATE TABLE OVELSEIOKT
	(
	OvelseID	INT	NOT NULL,
	OktID		INT	NOT NULL,
    PRIMARY KEY (OvelseID, OktID),
	FOREIGN KEY(OvelseID) REFERENCES OVELSE(OvelseID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(OktID) REFERENCES OKT(OktID) ON UPDATE CASCADE ON DELETE CASCADE
	);

CREATE TABLE INNGARI
	(
	OvelseID	INT	NOT NULL,
	GruppeID	INT	NOT NULL,
    PRIMARY KEY (OvelseID, GruppeID),
	FOREIGN KEY(OvelseID) REFERENCES OVELSE(OvelseID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(GruppeID) REFERENCES OVELSESGRUPPE(GruppeID) ON UPDATE CASCADE ON DELETE CASCADE
	);